apiVersion: v1
kind: Namespace
metadata:
  name: silver
---
apiVersion: v1
kind: Secret
metadata:
  name: artifactory-imagepullsecret
  namespace: silver
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <<Secret>>
---