# Default values for mtest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: art01-ic-plat-dev.jfrog.io/httpecho
  tag: v1
  pullPolicy: IfNotPresent

namespace:
  name: silver

deployment:
  name: frnt-dply
  version: v1

service:
  enabled: true
  type: ClusterIP
  port: 80
  name: frnt-api

appgateway:
  gwname: app-gw
  vsname: app-vs
  host: silver.red-stone.awscloud.io 

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    memory: 750Mi
  limits:
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}